// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emhhxcmifbfkrmlabnjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtaGh4Y21pZmJma3JtbGFibmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNzAxOTAsImV4cCI6MjA1Njc0NjE5MH0.9W9PeGpISZ-JtJz3BN3T-Gg3bpb85GhyHmJtM4MHr7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);